<a href="https://colab.research.google.com/github/Amulya77/TFF/blob/main/00_TF_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, some of fundamental concepts of tf

In this notebook we cover some of the most fundamental TensorFlow operations, more specifically:

*Introduction to tensors (creating tensors)

*Getting information from tensors (tensor attributes)

*Manipulating tensors (tensor operations)
Tensors and NumPy

*Using @tf.function (a way to speed up your regular Python functions)

*Using GPUs with TensorFlow

*Exercises to try

shift+enter==run code

ctrl+mm=markdown

ctrl+mb=new codecell

Intro to tensors

In [151]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [152]:
#create tensors with tf.constant() 
'''Creates a constant tensor from a tensor-like object.
tf.constant(
    value, dtype=None, shape=None, name='Const'
)'''
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [153]:
#check no of dimensions of tensor
scalar.ndim

0

In [154]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [155]:
#check dimension of vector
vector.ndim

1

In [156]:
#create a matrix(more tha 1 dim)
matrix= tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [157]:
matrix.ndim

2

In [158]:
#create another matrix
a_matrix=tf.constant([[10.,7.],
                      [3.,2.],
                      [8.,9.]],dtype=tf.float16)#specify the dtype with dtype parameter

a_matrix                      

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [159]:
#what is no of dimension of a_matrix?
a_matrix.ndim            # till now--total no of dim is no of element in shape 

2

In [160]:
#Lets create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [161]:
tensor.ndim   

# till now--total no of dim is no of element in shape 

3

What we created so far:

scalar: a single number. 

vector: a number with direction (e.g. wind speed with direction).

matrix: a 2-dimensional array of numbers.

tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

Creating tensors with variable

In [162]:
#create same tensor with tf.Variable 

changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7]) 
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [163]:
#Lets change a elemet in changable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [164]:
#How about we try  .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [165]:
#Lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

# **Note**:Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors,as TensorFlow does this for
you.However,if in doubt,use tf.constant and change it later if needed.

**Creating Random tensors**


In [166]:
#create random tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2)) 
random_2=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2=random_2.normal(shape=(3,2)) 

#Are they equal

random_1, random_2, random_1==random_2


#we have set seed thats why these are pseudo random 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in tensor

In [167]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [168]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

'''Wait... why didn't the numbers come out the same?

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.'''

In [169]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

*Exercise:Read through TensorFlow documentation on random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing5random tensors and shuffle them.

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [170]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)


#video timestamp-----1:41:00

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

###Other ways to make tensors

In [171]:
#Create tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [172]:
# Create tensors of all zeroes
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#we can also turn numpy arrays in tensorflow tensors

 The main difference between NumPy arrays and TensorFlow tensors is that
tensors can be run on a GPU(much faster for numerical computing)

In [173]:
#You can also turn Numpy arrays into tensors
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32) #Create a numpy array b/w 1 and 25
numpy_A

#X=tf.constant(some_matrix) #capital for some matrix or tensor
#y=tf.constant(vector)      #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [174]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [175]:
A=tf.constant(numpy_A,shape=(2,3,4)) #not work shape=(2,3,5) coz 30 elements
                                    #will work for shape=(8,3) coz 24 elements
B=tf.constant(numpy_A)
A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [176]:
2*3*4

24

### Getting information from tensors 

There will be times when you'll want to get different pieces of information from your tensors, in particular, you should know the following tensor vocabulary:

**Shape:** The length (number of elements) of each of the dimensions of a tensor.

**Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

**Axis or Dimension:** A particular dimension of a tensor.

**Size:** The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [177]:
#Create a rank 4 tensor
rank_4_tensor=tf.zeros(shape=[2,3,4,5] )
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [178]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [179]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [180]:
 2*3*4*5

120

In [181]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


###You can also index tensors just like Python lists.

In [182]:
 #gET THE FIRST TWO ELEMENTS OF EACH DIMENSION IN OUR TENSOR
 rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [183]:
somelist=[1,2,3,4]
somelist[:2]

[1, 2]

In [184]:
#get the first element from each dimension  execpt final
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [185]:
 rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [186]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [187]:
#Create a rank 2 tensor (2 dim) 
r_2_t=tf.constant([[10,7],
                  [3,4]])   
r_2_t.shape, r_2_t.ndim
r_2_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [188]:
#Getting last item of each row of our tensor
r_2_t[:,1:]


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [4]], dtype=int32)>

In [189]:
#Getting last item of each row of our tensor
r_2_t[:,-1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [190]:
somelist=[1,2,3,4]
somelist, somelist[-1]

([1, 2, 3, 4], 4)

In [191]:
#Add in extra dimension to our rank 2 tensor
r3t=r_2_t[...,tf.newaxis] #[:,:,tf.newaxis]
r3t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [192]:
#Alternative to tf.newaxis
tf.expand_dims(r_2_t,axis=-1) #-1 means final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [193]:
  tf.expand_dims(r_2_t,axis=0) #expand 0 axis 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

 ### Manipulating tensors(tensor Operations)


Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

Basic operations
You can perform many of the basic mathematical operations directly on tensors using Python operators such as, +, -, *. 

In [194]:
#we can add values to a tensor using addition operator
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [195]:
#Original tensor is unchanged
tensor=tensor+10
tensor  

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [196]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [197]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [198]:
#We can use the tf builtin  fncn

tf.multiply(tensor,10)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [199]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [200]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [201]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

**Matrix Multiplication**

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 5) @ (3, 5) won't work

(5, 3) @ (3, 5) will work

(3, 5) @ (5, 3) will work

The resulting matrix has the shape of the outer dimensions:

(5, 3) @ (3, 5) -> (5, 5)

(3, 5) @ (5, 3) -> (3, 3)



🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [202]:
#matrix multiplicaation in tf
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [203]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [204]:
#matrix multiplication with "@"" operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [205]:
tensor.shape #same shape

TensorShape([2, 2])

In [206]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [207]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: ignored

In [ ]:
Y

In [ ]:
#Lets change the shape of y
tf.reshape(Y,shape=(2,3))

In [ ]:
#try to multiply x and reshaped y

X.shape, tf.reshape(Y,shape=(2,3)).shape

In [ ]:
#try to multiply x and reshaped y
X@tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

In [ ]:
#we can rehshape x also

tf.reshape(X,shape=(2,3)).shape, Y.shape

In [ ]:
#we can rehshape x also
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

In [ ]:
#Can do the same with transpose

X,tf.transpose(X),tf.reshape(X,shape=(2,3))

In [208]:
#Try mat mul with transpose rather than rehshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot Product**

Matrix multiplication is also refferd as the dot product .



*   `tf.matmul()`
*   `tf.tensordot()`



In [209]:
#Perform ot product on X and Y(requires X and Y to be transposed)
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [210]:
tf.tensordot(tf.transpose(X),Y, axes=1) 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [211]:
#perform matmul on X and Y(transposed)
tf.matmul(X,tf.transpose(Y)) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [212]:
#perform matmul on X and Y(reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3))) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [213]:
#Check Y and transpose Y

print("Normal Y:")
print(Y,'\n')

print("Y is reshaped  to :")
print(tf.reshape(Y,shape=(2,3)),'\n')

print("Y is transposed  to :")
print(tf.transpose(Y),'\n')

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y is reshaped  to :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y is transposed  to :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



  **So which should you use?**

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, **you will transpose (not reshape)** one of them in order to line them up.

###changing Datatype  of the tensor



In [214]:
#Create a new tensor with default datatype (float32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [215]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [216]:
#Change from float 32 to float 16 (reduced precision)
D= tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [217]:
#Change from int32 to float32
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [218]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

##ABSOLUTE VALUES

> Indented block



In [219]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [220]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Agrregating Tensors

**Agrregating Tensors=condensing them from mulyiple values down to a smaller amount of values**

Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax **reduce()_[action]**, such as:

tf.reduce_min() - find the minimum value in a tensor.

tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

tf.reduce_mean() - find the mean of all elements in a tensor.

tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [221]:
 #Create a random tensor with values b/w 0 and 100 of size 50
 E=tf.constant(np.random.randint(0,100,size=50))
 E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 86, 86, 25, 92, 52, 33, 85, 81, 33, 89, 44, 61,  8, 16, 82, 19,
       39, 62, 16, 51, 53, 17, 91, 14,  6, 76, 95, 18, 61, 44, 65, 44, 73,
        5, 63, 56, 30, 20, 88, 84,  2,  0, 18,  8, 77, 84, 85,  5, 66])>

In [222]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [223]:
#Find min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [224]:
#find max
 tf.reduce_max(E)

IndentationError: ignored

In [225]:
#find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [226]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2447>

In [227]:
# FInd the variance
tf.reduce_var(E) #wont work

AttributeError: ignored

In [ ]:
#FIND variance by importing tensorflow_probalbility function

import tenso
rflow_probability as tfp
tfp.stats.variance(E)

In [231]:
 #find standard deviation
 tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.204245>

In [232]:
tf.math.reduce_std(E) # Input must be either real or complex
#Check the dtype for type error

TypeError: ignored

In [233]:
#find the variance by math function
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=912.2964>

###FIND  POSITIONAL MAX AND MIN

In [234]:
#create a new tensor for finding positional max and min

tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [235]:
#Find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [236]:
#INdex on of our largest value index
F[tf.argmax(F)]



<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [237]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [240]:
#Check for equality
F[tf.argmax(F)]== tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [241]:
#find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [243]:
#find the index on positional min index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#sQUEEING a tensor(removing all dimmensions)


In [247]:
#create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [248]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [250]:
G_squeezid=tf.squeeze(G)
G_squeezid , G_squeezid.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

 ###ONE_HOT ENCODING

In [252]:
#Create a list of indices

some_list=[0,1,2,3]#could be red blue green

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [253]:
#Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="I LOVE EMMA",off_value="I ALSO LIKE EMILIA")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I LOVE EMMA', b'I ALSO LIKE EMILIA', b'I ALSO LIKE EMILIA',
        b'I ALSO LIKE EMILIA'],
       [b'I ALSO LIKE EMILIA', b'I LOVE EMMA', b'I ALSO LIKE EMILIA',
        b'I ALSO LIKE EMILIA'],
       [b'I ALSO LIKE EMILIA', b'I ALSO LIKE EMILIA', b'I LOVE EMMA',
        b'I ALSO LIKE EMILIA'],
       [b'I ALSO LIKE EMILIA', b'I ALSO LIKE EMILIA',
        b'I ALSO LIKE EMILIA', b'I LOVE EMMA']], dtype=object)>

 ### Squaring, log, square root
 

In [255]:
#create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#square